// biome-ignore lint/performance/noBarrelFile: intentional re-export from shared package
export {
  DashboardResponse,
  ErrorResponse,
  IdParams,
  ListShoesQuery,
  ListShoesResponse,
  MovementListQuery,
  OrderBody,
  OrderListItem,
  OrderListResponse,
  OrderResponse,
  ReportsResponse,
  ShoeBody,
  ShoeResponse,
  ShoeUpdateBody,
  StockMovementBody,
  StockMovementListItem,
  StockMovementResponse,
  SuccessResponse,
} from "@inventory/shared/schemas";

export type {
  DashboardResponseType,
  IdParamsType,
  ListShoesQueryType,
  ListShoesResponseType,
  MovementListQueryType,
  OrderBodyType,
  OrderListResponseType,
  OrderResponseType,
  PaginationQueryType,
  ShoeBodyType,
  ShoeResponseType,
  ShoeUpdateBodyType,
  StockMovementBodyType,
  StockMovementListItemType,
  StockMovementResponseType,
} from "@inventory/shared/types";
