// biome-ignore lint/performance/noBarrelFile: intentional re-export from shared package
export {
  DashboardResponse,
  type DashboardResponseType,
  ErrorResponse,
  IdParams,
  type IdParamsType,
  ListShoesQuery,
  type ListShoesQueryType,
  ListShoesResponse,
  type ListShoesResponseType,
  MovementListQuery,
  type MovementListQueryType,
  type PaginationQueryType,
  ShoeBody,
  type ShoeBodyType,
  ShoeResponse,
  type ShoeResponseType,
  ShoeUpdateBody,
  type ShoeUpdateBodyType,
  StockMovementBody,
  type StockMovementBodyType,
  StockMovementListItem,
  type StockMovementListItemType,
  StockMovementResponse,
  type StockMovementResponseType,
  SuccessResponse,
} from "@inventory/shared/schemas";
